apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: admin-app
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - port: 8080
    targetPort: 10000 # [CHANGED] Target Envoy instead of the app directly