spring:
  application:
    name: userservice
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,metrics
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      paymentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60000
        autoTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      authServiceRetry:
        maxAttempts: 4
        waitDuration: 2000
        exponentialBackoffMultiplier: 2
  timelimiter:
    instances:
      stockPriceServiceTimeLimiter:
        timeoutDuration: 3000ms
  rateLimiter:
    instances:
      dataFetchRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 0ms
  bulkhead:
    instances:
      imageProcessingBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 0ms
  threadpoolbulkhead:
    instances:
      reportGenerationBulkhead:
        coreThreadPoolSize: 5
        maxThreadPoolSize: 10
        queueCapacity: 25
        keepAliveDuration: 60s